spring.application.name=nathy

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.profiles.active=test
api.security.token.secret=${JWT_SECRET:my-secret-key}

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.data.mongodb.uri=mongodb://localhost:27017/minha_base


