spring.application.name=nathy

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.profiles.active=test
api.security.token.secret=${JWT_SECRET:my-secret-key}

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.data.cassandra.contact-points=localhost
spring.data.cassandra.port=9042
spring.data.cassandra.keyspace-name=mykeyspace
spring.data.cassandra.local-datacenter=datacenter1
spring.data.cassandra.username=cassandra
spring.data.cassandra.password=cassandra
